/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package YILDIRIMSUDENAZtreasurehuntgame;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class YILDIRIMSUDENAZMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public YILDIRIMSUDENAZMenu() {
        initComponents();
        setResizable(false);
        name_txt.setVisible(false);
        enter_btn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        start_btn = new javax.swing.JButton();
        score_btn = new javax.swing.JButton();
        name_txt = new javax.swing.JTextField();
        enter_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1066, 600));

        jPanel1.setMaximumSize(new java.awt.Dimension(1066, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1066, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1066, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start_btn.setBackground(new java.awt.Color(157, 185, 191));
        start_btn.setText("START GAME");
        start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btnActionPerformed(evt);
            }
        });
        jPanel1.add(start_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 180, 30));

        score_btn.setBackground(new java.awt.Color(157, 185, 191));
        score_btn.setText("SCOREBOARD");
        score_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                score_btnActionPerformed(evt);
            }
        });
        jPanel1.add(score_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 180, 30));

        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 160, 30));

        enter_btn.setBackground(new java.awt.Color(157, 185, 191));
        enter_btn.setText("ENTER");
        enter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_btnActionPerformed(evt);
            }
        });
        jPanel1.add(enter_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/YILDIRIMSUDENAZtreasurehuntgame/images/menubck.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_btnActionPerformed
        name_txt.setVisible(true);
        enter_btn.setVisible(true);

        name_txt.requestFocus();
    }//GEN-LAST:event_start_btnActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        String username = name_txt.getText().trim().toLowerCase();

        if (username.matches("^[a-zA-Z0-9]{3,15}$")) {
            new YILDIRIMSUDENAZLevel1(username).setVisible(true); 
            dispose(); 
        } else {
            JOptionPane.showMessageDialog(YILDIRIMSUDENAZMenu.this,
                    "Invalid username!\nOnly letters and numbers allowed.\nMust be 3-15 characters long.",
            "Invalid Entry",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_name_txtActionPerformed

    private void enter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_btnActionPerformed
        String username = name_txt.getText().trim();

        if (username.matches("^[a-zA-Z0-9]{3,15}$")) {
            new YILDIRIMSUDENAZLevel1(username).setVisible(true); 
            dispose();

        } else {
            JOptionPane.showMessageDialog(YILDIRIMSUDENAZMenu.this,
                    "Invalid username!\nOnly letters and numbers allowed.\nMust be 3-15 characters long.",
            "Invalid Entry",
                    JOptionPane.ERROR_MESSAGE
            );
            name_txt.setText("");
            name_txt.requestFocus();
        }
    }//GEN-LAST:event_enter_btnActionPerformed

    private void score_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_score_btnActionPerformed
        new YILDIRIMSUDENAZScoreBoard().setVisible(true);
        dispose();


    }//GEN-LAST:event_score_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YILDIRIMSUDENAZMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YILDIRIMSUDENAZMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YILDIRIMSUDENAZMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YILDIRIMSUDENAZMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YILDIRIMSUDENAZMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton score_btn;
    private javax.swing.JButton start_btn;
    // End of variables declaration//GEN-END:variables
}
